
export enum DeviceType {
  ROUTER = 'Router',
  SMART_LOCK = 'Smart Lock',
  CAMERA = 'Camera',
  TV = 'TV',
  LIGHT = 'Smart Light',
  NAS = 'NAS',
  THERMOSTAT = 'Thermostat',
  DECOY = 'Decoy Node',
  UNKNOWN = 'Unknown Node'
}

export enum SecurityStatus {
  SECURE = 'Secure',
  MONITORING = 'Monitoring',
  ISOLATING = 'Isolating',
  BLOCKED = 'Blocked',
  DECEPTION_ACTIVE = 'Deceiving',
  UNAUTHORIZED = 'Unauthorized',
  QUARANTINED = 'Quarantined',
  RATE_LIMITED = 'Rate Limited'
}

export enum ProtectionMode {
  LEARNING = 'Learning',
  PROTECTION = 'Protection'
}

export type RetentionPeriod = '24h' | '7d' | '30d' | '90d' | 'Forever';

export interface TelemetryEvent {
  timestamp: string;
  deviceId: string;
  volumeMB: number;
  port: number;
  protocol: string;
  destination: string;
  isOutbound: boolean;
}

export interface IntelligenceState {
  globalModelVersion: string;
  localPatternsLearned: number;
  federatedSharingActive: boolean;
  lastUpdateTimestamp: string;
  immunityScore: number; // 0-100
  evolutionStage: 'Static' | 'Learning' | 'Adaptive' | 'Predictive' | 'Evolved';
}

export interface Recommendation {
  id: string;
  deviceId: string;
  title: string;
  description: string;
  actionLabel: string;
  severity: 'Low' | 'Medium' | 'High';
  type: 'UPDATE' | 'ISOLATE' | 'REPLACE' | 'AUDIT';
}

export interface MitigationRecord {
  id: string;
  deviceId: string;
  deviceName: string;
  timestamp: string;
  action: SecurityStatus;
  previousStatus: SecurityStatus;
  reason: string;
  wasRolledBack: boolean;
}

export interface FirewallRule {
  id: string;
  deviceId: string;
  action: 'ALLOW' | 'BLOCK' | 'THROTTLE';
  direction: 'INBOUND' | 'OUTBOUND' | 'LATERAL' | 'ANY';
  target: string;
  protocol: string;
  reason: string;
  expiresAt?: string;
  isAutoGenerated: boolean;
}

export interface IoTDevice {
  id: string;
  name: string;
  type: DeviceType;
  ip: string;
  mac: string;
  criticality: number;
  vulnerabilityScore: number;
  anomalyScore: number;
  status: SecurityStatus;
  lastSeen: string;
  vendor: string;
  parentId?: string;
  isDecoy?: boolean;
  isAuthorized: boolean;
  isSafeMode?: boolean; // New: Restricted mode for new/untrusted devices
  fingerprintConfidence: number;
  detectedProtocols: string[];
  trafficSignature: string;
  behaviorBaseline?: BehaviorBaseline;
  vulnerabilityProfile?: VulnerabilityProfile;
}

export interface BehaviorBaseline {
  avgDailyVolumeMB: number;
  peakHourStart: number;
  peakHourEnd: number;
  allowedDomains: string[];
  typicalProtocols: string[];
  allowedPorts: number[];
  learningProgress: number;
  lastDriftUpdate: string;
  neuralConsistency: number;
}

export interface VulnerabilityProfile {
  firmwareVersion: string;
  firmwareAgeDays: number;
  knownCVEs: CVE[];
  weakAuthDetected: boolean;
  internetExposure: number;
  predictiveRiskScore: number;
  lastAuditDate: string;
}

export interface CVE {
  id: string;
  description: string;
  cvss: number;
}

export interface ThreatEvent {
  id: string;
  timestamp: string;
  sourceIp: string;
  targetDeviceId: string;
  type: 'Brute Force' | 'Port Scan' | 'Lateral Movement' | 'DDoS' | 'Unauthorized Access' | 'Behavioral Anomaly' | 'Botnet C2';
  severity: 'Low' | 'Medium' | 'High' | 'Critical';
  status: 'Detected' | 'Neutralized' | 'Deceived';
  confidence: number;
  isCorrelated: boolean;
  correlatedThreatIds?: string[];
  honeypotTriggered?: string;
  mitigationAction: string;
  aiReasoning?: string;
}

export interface Honeytoken {
  id: string;
  type: string;
  name: string;
  value: string;
  location: string;
  triggeredCount: number;
}

export interface DecoyConfig {
  id: string;
  name: string;
  type: DeviceType;
  vulnerabilityTarget: string;
  active: boolean;
  interactionLevel: 'High' | 'Low';
  hits: number;
}
