
import { FirewallRule, IoTDevice, DeviceType, SecurityStatus } from '../types';

export const firewallService = {
  /**
   * Generates default context-aware rules for a new device.
   */
  generateContextRules: (device: IoTDevice): FirewallRule[] => {
    const rules: FirewallRule[] = [];
    const baseId = `rule-${device.id.slice(-4)}`;

    switch (device.type) {
      case DeviceType.LIGHT:
        rules.push({
          id: `${baseId}-1`,
          deviceId: device.id,
          action: 'BLOCK',
          direction: 'OUTBOUND',
          target: 'Internet',
          protocol: 'ANY',
          reason: 'Context Policy: Smart Bulbs forbidden from WAN egress.',
          isAutoGenerated: true
        });
        break;
      case DeviceType.CAMERA:
        rules.push({
          id: `${baseId}-1`,
          deviceId: device.id,
          action: 'BLOCK',
          direction: 'LATERAL',
          target: 'TV/Entertainment',
          protocol: 'ANY',
          reason: 'Context Policy: Surveillance nodes prohibited from inter-VLAN access.',
          isAutoGenerated: true
        });
        break;
      case DeviceType.SMART_LOCK:
        rules.push({
          id: `${baseId}-1`,
          deviceId: device.id,
          action: 'ALLOW',
          direction: 'INBOUND',
          target: 'Core Gateway',
          protocol: 'TLS/MQTT',
          reason: 'Context Policy: Trusted controller-only communication.',
          isAutoGenerated: true
        });
        break;
    }

    return rules;
  },

  /**
   * Tightens policy automatically after suspicious behavior.
   */
  tightenPolicy: (device: IoTDevice, anomalyScore: number): FirewallRule => {
    const expiresAt = new Date(Date.now() + 15 * 60 * 1000).toISOString(); // 15 min TTL
    
    return {
      id: `tighten-${Math.random().toString(36).substr(2, 5)}`,
      deviceId: device.id,
      action: anomalyScore > 0.8 ? 'BLOCK' : 'THROTTLE',
      direction: 'ANY',
      target: 'ALL_TRAFFIC',
      protocol: 'ANY',
      reason: `Auto-Policy Tightening: High anomaly score (${(anomalyScore * 10).toFixed(1)}) detected.`,
      expiresAt,
      isAutoGenerated: true
    };
  }
};
